### ISSUE TITLE
Atom freezes up when running `atom .` shell command from OSX home directory

### ISSUE THREAD

**Issue by davelaflam** [benjaminRomano/bottom-dock#12]
I was messing around with this package and notice a slight bug. I'm currently on OSX 10.11.4 and if you run `atom .` from the home directory `~/Users/userName` while the bottom-dock package is enabled, Atom will freeze up and is unresponsive. If you try closing Atom or wait just a few, Atom will display the following message: 
"Editor is not responding, 
The editor is not responding. Would you like to force close it or just keep waiting?"

If you click Keep waiting, the app is still unresponsive and at some point you just need to click "close".

If I disable the bottom-dock package, then run the `atom .` command from the `~/Users/userName` home directory Atom will open and displays the file tree structure as it should. 

I'm not aware of any log files that I could include for your debugging, however, please let me know if there's any additional information that would be helpful.

**Comment by benjaminRomano** [comment]
What packages are you using that interacts with bottom dock? (i.e. Linter-manager). 
Also, I currently don't have a Mac machine so I won't be able to test in that environment. I'll take a look and see if I can reproduce the bug on Linux. Thanks for filing this issue.

**Comment by davelaflam** [comment]
I don't think it has anything to do with the various linters but here's what I have installed.

I use the main Linter - https://atom.io/packages/linter along with:
linter-coffeelint
linter-csslint
linter-eslint
linter-jscs
linter-jshint
linter-pep8
linter-scss-lint

As far as a Mac machine to test on. I would ask a colleague who is using a Mac to install the package and then run the `atom .` command from their home directory. That should reproduce the error so you can see what's happening.
