### ISSUE TITLE
vertical dock?

### ISSUE THREAD

**Issue by selfagency** [benjaminRomano/bottom-dock#14]
i use an ultra-wide screen. i would love it if there was an option to have the bottom-dock appear as a side-dock instead, with vertical panels instead of horizontal ones. please consider this as an option!

**Comment by benjaminRomano** [comment]
Unfortunately, I won't be able to implement that. It would require a big rewrite and I no longer maintain these atom packages (I've switched to vs code). However,  you are welcome to create a PR if you are interested.
