### ISSUE TITLE
Better tags on atom.io

### ISSUE THREAD

**Issue by jonyeezs** [benjaminRomano/bottom-dock#16]
Be nice if you could add a tag bottom-dock to any projects (obviously the ones you own) that uses bottom-dock.

And perhaps update contributing readme to have users who create new packages with the tag bottom-dock.

This would allow an easy way to see what plugins are related to bottom-dock

**Comment by benjaminRomano** [comment]
Thanks for the suggestion, @jonyeezs. I'll add the following tags and update the README.md the next time I publish a new version of bottom-dock.
