### ISSUE TITLE
HTML in Pane Title

### ISSUE THREAD

**Issue by keplersj** [benjaminRomano/bottom-dock#2]
Would it be possible to put HTML in the title of a pane for mild customization. For example with this one could add a badge next to the title of their pane.

**Comment by benjaminRomano** [comment]
Yeah that's a good idea. I'll add that :+1:

**Comment by keplersj** [comment]
Awesome!

**Comment by benjaminRomano** [comment]
Added customizable tabs in f6ad32928d3943481a3d3e0c5e30778c8969ed6a.
