### ISSUE TITLE
Start panel closed

### ISSUE THREAD

**Issue by simoncoulton** [benjaminRomano/bottom-dock#3]
Is there the ability for the dock to be closed by default when opening Atom?

**Comment by benjaminRomano** [comment]
Not at the moment. I'll make that configurable

**Comment by simoncoulton** [comment]
That'd be awesome, thanks :+1:

**Comment by benjaminRomano** [comment]
I added an option to start open or closed in v0.2.2. Can you verify that worked? Thanks

**Comment by simoncoulton** [comment]
Works a treat, thanks mate :)
