### ISSUE TITLE
Auto opening dock on every window reload

### ISSUE THREAD

**Issue by laughedelic** [benjaminRomano/bottom-dock#4]
I'm using todo-manager plugin, but I guess, the issue is related to the bottom dock. Since some recent update (I can't tell precisely), the dock automatically opens on every window reload (or just opening a new project). If it's an intended behaviour, I would like it to be optional.

**Comment by benjaminRomano** [comment]
Are you on v0.2.2? I just added an option to set whether or not to start open earlier today.

**Comment by laughedelic** [comment]
:laughing: haha :+1: 
Actually, I've updated before posting this issue, but the plugin settings didn't update until I reloaded the window.. Thanks!

**Comment by laughedelic** [comment]
I have this problem again. The setting is off, but every new window has the panel open..

**Comment by benjaminRomano** [comment]
Just made some changes. This should be fixed in v0.3.3

**Comment by laughedelic** [comment]
Seems to be fine now. thanks!
