### ISSUE TITLE
An option to hide the tabs panel

### ISSUE THREAD

**Issue by laughedelic** [benjaminRomano/bottom-dock#5]
I use only todo-manager plugin with this dock and I think that this panel with **one** open tab is not very useful for me. It takes space on the screen and the highlighted tab is a bit distracting. Regarding the controls, they could be useful, but I still can access them with the hotkeys. 
So what I'm asking for is an option to hide this panel if there is only one tab (or some keybinding to toggle it?).

**Comment by benjaminRomano** [comment]
So, I've given some thought about the best way to handle one panel, and I think I'm going to handle it the same way visual studio does.

They hide the tabs when there is only one panel. As show below in the picture.

##### 1 Panel

![image](https://cloud.githubusercontent.com/assets/9221137/9291828/9d7391b0-439b-11e5-94f4-4128a855c8ad.png)

##### multiple panels

![image](https://cloud.githubusercontent.com/assets/9221137/9291834/5c249636-439c-11e5-9971-23b78e065d17.png)

In making this change, I would also copy the way Visual Studio handles the close button by creating a header on the panel.

What do you think about this approach? Do you think the header is just as annoying?

**Comment by wldcordeiro** [comment]
Settings view: checkboxes for panels to show/enable. Simplest solution imo.

**Comment by benjaminRomano** [comment]
I already fixed this problem. I just made it that if only one tab is present than it hides the tab panel.

**Comment by laughedelic** [comment]
thanks :+1:
