### ISSUE TITLE
Feature Suggestion : Toggle button on dock

### ISSUE THREAD

**Issue by puranjayjain** [benjaminRomano/bottom-dock#7]
@benjaminRomano would a toggle button on the bottom dock just to the left of the close button be a nice addition to the dock? What are tour thoughts about it

**Comment by benjaminRomano** [comment]
I agree it would be nice to have a toggle button. 

I'll add it to the status bar so it can be toggled on and off.

**Comment by puranjayjain** [comment]
@benjaminRomano feel free to ask for help if you want :smile:

**Comment by benjaminRomano** [comment]
Added the ability to toggle in the status bar. If you notice any bugs or have any suggestions please feel free to let me know. :smile:

![image](https://cloud.githubusercontent.com/assets/9221137/13841672/4fcc555e-ebf8-11e5-8cd3-e99571e3de9d.png)

**Comment by puranjayjain** [comment]
@benjaminRomano that's freaking awesome dude kudos!

**Comment by puranjayjain** [comment]
@benjaminRomano one more suggestion can you add tooltip text to the three icon buttons on the left so a new user may know what they do when they hover over it?

**Comment by benjaminRomano** [comment]
I added tooltips to the buttons in the grunt/gulp manager packages

**Comment by puranjayjain** [comment]
great i'm closing the issue now I think its resolved for now. Anyway there are a lot of feature requests in this one :smile:
