### ISSUE TITLE
Clicking bottom-dock close button won't allow bottom dock to open

### ISSUE THREAD

**Issue by chocolatetoothpaste** [benjaminRomano/bottom-dock#8]
I don't know if this is a new bug from a recent update.  I can use my hot key combo to toggle it open and closed, and I can click the "Bottom Dock" item in the bottom status bar, this also successfully toggles the dock open/closed.  If I click the close button in the bottom dock, I cannot open it again until I close atom and reopen it.  Atom v1.5.4, bottom-dock v0.4.0, ubuntu v 15.10.  Thanks for your hard work, I love this plug in!

**Comment by benjaminRomano** [comment]
The close button (X) deletes the current pane and when there are no panes present bottom-dock is hidden. Bottom-dock will not re-show until you add a pane and toggle it to show

I'll look and see if I can make this bevhaiour more clear since a lot of people have been confused by it.

**Comment by chocolatetoothpaste** [comment]
Oh, that makes a bit more sense.  I only use bottom-dock for the gulp plug-in (at least for now), so I personally don't have use for a button to remove a pane.  I would have assumed if I wanted a pane removed I would just disable/remove the plug-in.  My assumption was the "x" was just a toggle-close button.  Just my 2 cents...

**Comment by benjaminRomano** [comment]
I've decided to remove the close button. It has been causing more confusion than helping.

**Comment by EHLOVader** [comment]
I miss the close button, what if you had a close button on the tabs which closed the tabs like you have on documents.
<img src="https://i.imgur.com/Rdo91mO.png" height="50px">

And offer escape key to hide the bottom-dock like other panes have for their docks.

**Comment by benjaminRomano** [comment]
I'm no longer maintaining this package as I've switched editors. Please feel free to make a pr. all those suggestions sound good to me
