### ISSUE TITLE
Falsely indicating 2 issues in parentheses though none exist

### ISSUE THREAD

**Issue by brettz9** [benjaminRomano/bottom-dock#9]
Though I have no current linting errors, bottom dock shows up in red with "2" listed in parentheses and when clicked, shows no issues within itself either.

**Comment by benjaminRomano** [comment]
Hey brettz9 could you post a screenshot of the bug. Also which linters were you using

**Comment by brettz9** [comment]
![bd1](https://cloud.githubusercontent.com/assets/20234/14023064/df3339e0-f19f-11e5-9646-70c3b07a97fb.png)
![bd2](https://cloud.githubusercontent.com/assets/20234/14023063/df33557e-f19f-11e5-9131-0007c8772eae.png)

As per the screenshots, the linters are todo-manager and linter-eslint. linter and linter-manager are also installed as are linter-csslint, linter-htmlhint, linter-jsonlint, linter-markdown, linter-package-json-validator, linter-xmllint.

**Comment by benjaminRomano** [comment]
The 2 in the bottom right indicates that you currently have two panes open in bottom-dock (TODO and linter) and the red eye indicates bottom dock isn't currently visible

**Comment by brettz9** [comment]
Hmm, oops. :)  Ok, well, could I request then that the color be changed from red because that is a color I very much notice and sets off alarm bells.

Also, even the parentheses trigger the idea of problems for me, and I'm not sure what benefit indicating them has (unless it is to be a reminder that the number available may change with each document type).

**Comment by benjaminRomano** [comment]
Yeah that's understandable. I'll change the color scheme and remove the parentheses (not really sure why I included them in the first place :smile:)

**Comment by brettz9** [comment]
Thanks!  As far as why you included them, I can see one scenario where having a number in parentheses (and color) there would be useful, and that is if one has disabled "Display Linter Info in the Status Bar" and/or "Display Linter Status Info in the Status Bar" within the base "linter", one might wish to opt to show the error status and number of errors there instead. Not a pressing need for me at least though.

Btw, speaking of colors, is it possible to opt for them within the expanded Bottom Dock table, e.g., how "Error" shows up in red in the default linter display?

**Comment by brettz9** [comment]
Btw, I updated to your latest version and the color is gone, but the parentheses (and the option for them) are still present.

One weird thing too I just noticed is that when I click on the "Report issue" or "CHANGELOG", etc. with the settings page for your package, it repeats the action two times, e.g., opens two report issue tabs in the browser. This didn't happen with the settings for another package I tested which strikes me as weird, as I'd think this would be controlled by Atom and not sure why it'd happen for your package specifically.

**Comment by benjaminRomano** [comment]
So the parentheses are still showing in the status bar? If they are you might want to re-install the bottom-dock package since they shouldn't be there anymore.

Can you file a new issue for the color highlighting of errors. I'll try to get around to that when I have a bit more time. 

Lastly, I think the two report issue tabs being opened is probably just some weird Atom bug.

**Comment by brettz9** [comment]
No, the parentheses now aren't showing anymore. Ok, I can file a new issue.
